###
POST http://localhost:5001/api/products/seed/
Content-Type: application/json

{
      "products": [
      {
            "name": "Nick Slim Shirt",
            "category": "Shirts",
            "image": "/images/p1.jpg",
            "price": 120,
            "countInStock": 10,
            "brand": "Nick",
            "rating": 2.5,
            "numReviews": 10,
            "description": "high quality product"
      },
      {
            "name": "Adidas Slim Shirt",
            "category": "Shirts",
            "image": "/images/p2.jpg",
            "price": 100,
            "countInStock": 15,
            "brand": "Adidas",
            "rating": 4.0,
            "numReviews": 10,
            "description": "high quality product"
      },
      {
            "name": "Lacoste Slim Shirt",
            "category": "Shirts",
            "image": "/images/p3.jpg",
            "price": 220,
            "countInStock": 0,
            "brand": "Lacoste",
            "rating": 4.8,
            "numReviews": 10,
            "description": "high quality product"
      },
      {
            "name": "Nick Slim Pant",
            "category": "Pants",
            "image": "/images/p4.jpg",
            "price": 78,
            "countInStock": 50,
            "brand": "Nick",
            "rating": 4.5,
            "numReviews": 14,
            "description": "high quality product"
      },
      {
            "name": "Puma Slim Pant",
            "category": "Pants",
            "image": "/images/p5.jpg",
            "price": 65,
            "countInStock": 190,
            "brand": "Puma",
            "rating": 4.5,
            "numReviews": 10,
            "description": "high quality product"
      },
      {
            "name": "Adidas Fit Pant",
            "category": "Pants",
            "image": "/images/p6.jpg",
            "price": 139,
            "countInStock": 255,
            "brand": "Adidas",
            "rating": 4.5,
            "numReviews": 10,
            "description": "high quality product"
      }
      ]
 
}

###

POST http://localhost:3001/api/users/signin 
Content-Type: application/json

{
      "email":  "medo12089@yahoo.com",
      "password": "1234"
}